//Nodejs allows us to create and handle custom events using events module. Each Event module contains a class called EventEmitter whose object could be used to raise and handle Custom Events...
var events = require('events');
var ev = new events.EventEmitter();//creating the object....
//handling the event...
ev.on('firstEvent', function(data){
	console.log(data);
	console.log("Event called firstevent is triggered");
})

//raising the event...
ev.emit('firstEvent', "Hai from the Raiser...")